name: example
description: Examples using dartantic_ai.
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  chrono_dart: ^2.0.2
  cross_file: ^0.3.4+2
  dartantic_ai:
    path: ..
  dartantic_interface:
    path: ../../dartantic_interface
  dotprompt_dart: ^0.5.0
  freezed_annotation: ^3.1.0
  http: ^1.4.0
  json_annotation: ^4.9.0
  json_schema: ^5.2.1
  logging: ^1.3.0
  openai_core: ^0.10.1
  soti_schema_plus: ^1.3.0

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
