name: chatarang
description: A chat agent that uses Dartantic.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  all_lint_rules_community: ^0.0.43
  cli_repl: ^0.2.3
  dartantic_ai: ^2.0.0
  dartantic_interface: ^2.0.0
  http: ^1.4.0
  json_schema: ^5.2.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
