name: dartantic_interface
description: Interface definitions for dartantic_ai for use in building custom providers.
version: 2.0.0
repository: https://github.com/csells/dartantic_ai
homepage: https://docs.dartantic.ai
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  cross_file: ^0.3.5+1
  json_schema: ^5.2.2
  logging: ^1.3.0
  meta: ^1.17.0
  mime: ^2.0.0
  path: ^1.9.1
  uuid: ^4.5.2

dev_dependencies:
  all_lint_rules_community: ^0.0.43
